package io.avalia.samba;

import org.junit.Assert;
import org.junit.Test;

/**
 * *** IMPORTANT WARNING : DO NOT EDIT THIS FILE ***
 * 
 * This file is used to specify what you have to implement. To check your work,
 * we will run our own copy of the automated tests. If you change this file,
 * then you will introduce a change of specification!!!
 * 
 * @author Olivier Liechti
 */
public class BanjoTest {
	
	@Test
	public void aBanjoShouldMakeTan() {
		IInstrument banjo = new Banjo();
		String sound = banjo.play();
		Assert.assertEquals("tan", sound);
	}

	@Test
	public void aBanjoShouldBeLouderThanAFlute() {
		IInstrument banjo = new Banjo();
		IInstrument flute = new Flute();
		int banjoVolume = banjo.getSoundVolume();
		int fluteVolume = flute.getSoundVolume();
		Assert.assertTrue(banjoVolume > fluteVolume);
	}

	@Test
	public void aBanjoShouldBeBrown() {
		IInstrument trumpet = new Banjo();
		String color = trumpet.getColor();
		Assert.assertEquals("brown", color);
	}

}
