package io.avalia.samba;

import org.junit.Assert;
import org.junit.Test;

/**
 * *** IMPORTANT WARNING : DO NOT EDIT THIS FILE ***
 * 
 * This file is used to specify what you have to implement. To check your work,
 * we will run our own copy of the automated tests. If you change this file,
 * then you will introduce a change of specification!!!
 * 
 * @author Olivier Liechti
 */
public class PianoTest {

	@Test
	public void aPianoShouldMakePlink() {
		IInstrument piano = new Piano();
		String sound = piano.play();
		Assert.assertEquals("plink", sound);
	}

	@Test
	public void aPianoShouldBeBrown() {
		IInstrument piano = new Piano();
		String color = piano.getColor();
		Assert.assertEquals("brown", color);
	}
	
	@Test
	public void aPianoShouldBeAtLeastFiveTimesLouderThanAFlute() {
		IInstrument piano = new Piano();
		IInstrument flute = new Flute();
		int pianoVolume = piano.getSoundVolume();
		int fluteVolume = flute.getSoundVolume();
		Assert.assertTrue(pianoVolume >= (fluteVolume * 5));
	}

}
